# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Owner\Documents\geodata_manager\geodata_manager001\src\gui\components\qt_designer\qt_files//qt_add_site_data_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSiteDataDlg(object):
    def setupUi(self, AddSiteDataDlg):
        AddSiteDataDlg.setObjectName("AddSiteDataDlg")
        AddSiteDataDlg.resize(741, 624)
        self.gridLayout = QtWidgets.QGridLayout(AddSiteDataDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AddSiteDataDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddSiteDataDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(AddSiteDataDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.MakePrimaryCB = QtWidgets.QCheckBox(AddSiteDataDlg)
        self.MakePrimaryCB.setChecked(True)
        self.MakePrimaryCB.setObjectName("MakePrimaryCB")
        self.gridLayout.addWidget(self.MakePrimaryCB, 3, 4, 1, 1)
        self.NameLE = QtWidgets.QLineEdit(AddSiteDataDlg)
        self.NameLE.setObjectName("NameLE")
        self.gridLayout.addWidget(self.NameLE, 3, 3, 1, 1)
        self.SelectFeature_comboBox = QtWidgets.QComboBox(AddSiteDataDlg)
        self.SelectFeature_comboBox.setObjectName("SelectFeature_comboBox")
        self.gridLayout.addWidget(self.SelectFeature_comboBox, 3, 1, 1, 1)
        self.SelectShapefile_pushButton = QtWidgets.QPushButton(AddSiteDataDlg)
        self.SelectShapefile_pushButton.setObjectName("SelectShapefile_pushButton")
        self.gridLayout.addWidget(self.SelectShapefile_pushButton, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(AddSiteDataDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(AddSiteDataDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.CommentsTextEdit = QtWidgets.QTextEdit(AddSiteDataDlg)
        self.CommentsTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.CommentsTextEdit.setObjectName("CommentsTextEdit")
        self.gridLayout.addWidget(self.CommentsTextEdit, 4, 1, 1, 4)
        self.Path_lineEdit = QtWidgets.QLineEdit(AddSiteDataDlg)
        self.Path_lineEdit.setObjectName("Path_lineEdit")
        self.gridLayout.addWidget(self.Path_lineEdit, 0, 1, 1, 4)

        self.retranslateUi(AddSiteDataDlg)
        self.buttonBox.rejected.connect(AddSiteDataDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(AddSiteDataDlg)

    def retranslateUi(self, AddSiteDataDlg):
        _translate = QtCore.QCoreApplication.translate
        AddSiteDataDlg.setWindowTitle(_translate("AddSiteDataDlg", "Add site data"))
        self.label.setText(_translate("AddSiteDataDlg", "Select data type"))
        self.label_2.setText(_translate("AddSiteDataDlg", "Name"))
        self.MakePrimaryCB.setText(_translate("AddSiteDataDlg", "Set as primary"))
        self.SelectShapefile_pushButton.setText(_translate("AddSiteDataDlg", "Select Shapefile"))
        self.label_3.setText(_translate("AddSiteDataDlg", "Comments"))
        self.CommentsTextEdit.setPlaceholderText(_translate("AddSiteDataDlg", "Optional"))

